-- ============================================================
--  V1__init.sql - Schéma initial Lake Diving Reservation
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    name                VARCHAR(255) NOT NULL,
    role                VARCHAR(50)  NOT NULL DEFAULT 'GUEST',
    reset_token         VARCHAR(255),
    reset_token_expiry  TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dive_slots (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date    DATE         NOT NULL,
    start_time   TIME         NOT NULL,
    end_time     TIME         NOT NULL,
    diver_count  INTEGER      NOT NULL,
    title        VARCHAR(255),
    notes        TEXT,
    created_by   BIGINT       NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_dive_slots_date ON dive_slots(slot_date);
CREATE INDEX IF NOT EXISTS idx_dive_slots_created_by ON dive_slots(created_by);

CREATE TABLE IF NOT EXISTS app_config (
    config_key   VARCHAR(255) PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
