-- V23 — Liste d'attente pour l'auto-inscription des plongeurs
-- Ajoute les champs d'ouverture des inscriptions sur dive_slots
-- et crée la table waiting_list_entries.

ALTER TABLE dive_slots ADD COLUMN registration_open     BOOLEAN   NOT NULL DEFAULT FALSE;
ALTER TABLE dive_slots ADD COLUMN registration_opens_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS waiting_list_entries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id           BIGINT       NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    level             VARCHAR(50)  NOT NULL,
    number_of_dives   INTEGER      NOT NULL,
    last_dive_date    DATE         NOT NULL,
    prepared_level    VARCHAR(50),
    comment           TEXT,
    registered_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (slot_id) REFERENCES dive_slots(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_waiting_list_slot_id  ON waiting_list_entries(slot_id);
CREATE INDEX IF NOT EXISTS idx_waiting_list_email    ON waiting_list_entries(email);
