-- V2: Ajout de la table des plongeurs inscrits sur un créneau
CREATE TABLE IF NOT EXISTS slot_divers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id     BIGINT       NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    level       VARCHAR(50)  NOT NULL,
    added_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (slot_id) REFERENCES dive_slots(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_slot_divers_slot_id ON slot_divers(slot_id);

