-- Plongées multiples par créneau (ex : matin + après-midi)
-- Chaque slot peut contenir plusieurs slot_dives; chaque palanquée appartient
-- optionnellement à une slot_dive (null = mode classique sans organisation par plongée)

CREATE TABLE slot_dives (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id    BIGINT NOT NULL REFERENCES dive_slots(id) ON DELETE CASCADE,
    dive_index INT    NOT NULL DEFAULT 1,
    label      VARCHAR(255),
    start_time TIME,
    end_time   TIME,
    depth      VARCHAR(50),
    duration   VARCHAR(50)
);

ALTER TABLE palanquees ADD COLUMN slot_dive_id BIGINT REFERENCES slot_dives(id) ON DELETE SET NULL;
