-- Table de jointure pour les membres des palanquées
-- Remplace le FK palanquee_id sur slot_divers afin qu'un plongeur puisse
-- participer à plusieurs plongées d'un même créneau multi-plongées.

CREATE TABLE palanquee_members (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palanquee_id  BIGINT NOT NULL REFERENCES palanquees(id) ON DELETE CASCADE,
    slot_diver_id BIGINT NOT NULL REFERENCES slot_divers(id) ON DELETE CASCADE,
    position      INT    NOT NULL DEFAULT 0,
    UNIQUE(palanquee_id, slot_diver_id)
);

-- Migrer les assignations existantes avant de supprimer les anciennes colonnes
INSERT INTO palanquee_members (palanquee_id, slot_diver_id, position)
SELECT palanquee_id, id, palanquee_position
FROM slot_divers
WHERE palanquee_id IS NOT NULL;

-- Supprimer les anciennes colonnes devenues inutiles
ALTER TABLE slot_divers DROP COLUMN palanquee_id;
ALTER TABLE slot_divers DROP COLUMN palanquee_position;
