-- V41 — Fiches de sécurité liées aux créneaux
-- Permet au DP d'uploader les fiches de sécurité post-plongée (images / PDF).

CREATE TABLE IF NOT EXISTS slot_safety_sheets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id       BIGINT        NOT NULL,
    uploader_id   BIGINT,
    original_name VARCHAR(255)  NOT NULL,
    stored_name   VARCHAR(255)  NOT NULL,
    file_path     VARCHAR(500)  NOT NULL,
    content_type  VARCHAR(100)  NOT NULL,
    file_size     BIGINT        NOT NULL,
    uploaded_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at    TIMESTAMP     NOT NULL,
    FOREIGN KEY (slot_id)     REFERENCES dive_slots(id) ON DELETE CASCADE,
    FOREIGN KEY (uploader_id) REFERENCES users(id)      ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_slot_safety_sheets_slot_id ON slot_safety_sheets(slot_id);
