-- V42 — Sessions de plongée libres (sans créneau)
-- Permet à un DP d'organiser des palanquées en dehors du système de créneaux.
-- Max 15 sessions par utilisateur (régle appliquée en code).

-- Table principale : une session de plongée libre rattachée à son propriétaire (DP)
CREATE TABLE free_dive_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label      VARCHAR(255),
    dive_date  DATE         NOT NULL,
    start_time TIME         NOT NULL,
    notes      TEXT,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_free_sessions_owner ON free_dive_sessions(owner_id);

-- Plongées d'une session (ex : matin + après-midi)
CREATE TABLE free_session_dives (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES free_dive_sessions(id) ON DELETE CASCADE,
    dive_index INT          NOT NULL DEFAULT 1,
    label      VARCHAR(255),
    start_time TIME,
    end_time   TIME,
    depth      VARCHAR(50),
    duration   VARCHAR(50)
);

-- Plongeurs d'une session (pas de limite de capacité)
CREATE TABLE free_session_divers (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT       NOT NULL REFERENCES free_dive_sessions(id) ON DELETE CASCADE,
    first_name        VARCHAR(100) NOT NULL,
    last_name         VARCHAR(100) NOT NULL,
    level             VARCHAR(100) NOT NULL,
    email             VARCHAR(255),
    phone             VARCHAR(50),
    is_director       BOOLEAN      NOT NULL DEFAULT FALSE,
    aptitudes         VARCHAR(255),
    license_number    VARCHAR(100),
    medical_cert_date DATE,
    comment           TEXT,
    club              VARCHAR(100),
    added_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Palanquées d'une session
CREATE TABLE free_palanquees (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT       NOT NULL REFERENCES free_dive_sessions(id) ON DELETE CASCADE,
    dive_id    BIGINT       REFERENCES free_session_dives(id) ON DELETE SET NULL,
    name       VARCHAR(100) NOT NULL,
    position   INT          NOT NULL DEFAULT 0,
    depth      VARCHAR(50),
    duration   VARCHAR(50)
);

-- Appartenance plongeur ↔ palanquée (miroir de palanquee_members)
CREATE TABLE free_palanquee_members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palanquee_id BIGINT NOT NULL REFERENCES free_palanquees(id) ON DELETE CASCADE,
    diver_id     BIGINT NOT NULL REFERENCES free_session_divers(id) ON DELETE CASCADE,
    position     INT    NOT NULL DEFAULT 0,
    aptitudes    VARCHAR(255),
    UNIQUE(palanquee_id, diver_id)
);
