-- V43 — Partage de sessions libres entre directeurs de plongée
-- Un DP peut partager une de ses sessions avec un autre DP en lecture ou en écriture.
-- Les sessions partagées ne comptent pas dans le quota des 15 sessions pour le destinataire.

CREATE TABLE free_session_shares (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT      NOT NULL REFERENCES free_dive_sessions(id) ON DELETE CASCADE,
    shared_with_id  BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_level    VARCHAR(10) NOT NULL DEFAULT 'READ',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(session_id, shared_with_id)
);

CREATE INDEX idx_free_session_shares_session ON free_session_shares(session_id);
CREATE INDEX idx_free_session_shares_user    ON free_session_shares(shared_with_id);
